# netlify.toml

# Build settings
[build]
  # Change directory to the frontend folder
  base = "frontend/"
  command = "npx vite build" # Adjust the build command to execute within the frontend folder
  publish = "frontend/dist/" # Publish the build output from the frontend folder

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/frontend/index.html"
  status = 200
